epc<-read.table("household_power_consumption.txt",sep=";",header=TRUE)
epc2<-filter(epc,EPCDate=="1/2/2007" | EPCDate=="2/2/2007")
rm(epc)
epc2<-filter(epc2,Global_active_power!="?")
epc2<-mutate(epc2,Global_active_power=as.numeric(Global_active_power))
epc2<-mutate(epc2,EPCDT=dmy_hms(paste(EPCDate,EPCTime)))
epc2<-mutate(epc2,EPCDTN=as.numeric(EPCDT))
png(filename = "plot2.png",width = 480, height = 480)
plot(epc2$EPCDTN,epc2$Global_active_power,type='l',xlab="",ylab="Global Active Power (kilowatts)",xaxt="n")
axis(1,labels=c("Thu","Fri","Sat"),at=c(min(epc2$EPCDTN),mean(epc2$EPCDTN),max(epc2$EPCDTN)))
dev.off()
